### ISSUE TITLE
[Enable] Enable LTP subtests when lsds/sgx-lkl/#236 (357) is fixed

### ISSUE THREAD

**Issue by hukoyu** [lsds/ltp#14]
We disabled subtests of LTP tests for below syscalls due to bug lsds/sgx-lkl#236
Look for 236 or 357 in the TODO comments in the related PRs to enable subtests back after issue fixed.
(P.S: 357 resolved as dupe of 236)

Syscalls: (Count: 7)
chmod03
chmod04
fchmod03
fchmod04
fchown03
utime02
utime05

**Comment by SeanTAllen** [comment]
PR coming soon that fixes the sgx-lkl issue and enables these tests.
