### ISSUE TITLE
[Confirm] Some fcntl tests not supported due to single process limitation

### ISSUE THREAD

**Issue by hukoyu** [lsds/ltp#21]
Below fcntl tests are not supported due to single process limitation of sgx-lkl and no fork support. @davidchisnall  can you confirm please, after you confirm we will categorize these tests as not supported and these LTP tests will remain disabled:

1) fcntl07 https://github.com/lsds/ltp/blob/sgx-lkl/testcases/kernel/syscalls/fcntl/fcntl07.c

The test verifies the below using execlp( ) system call
 1. test close-on-exec with a regular file
 2. test close-on-exec with a pipe
 3. test close-on-exec with a fifo
The parent process creates a child and execute execlp( ) for each of above scenarios on respective fd's.
The parent process waits for the child process status and updates the test results accordingly.
The system call execlp is not supported in sgx-lkl environment as internally fork( ) is used by execlp.
execlp replaces the current process with a new process and the context is lost in sgx-lkl.

2) fcntl11 https://github.com/lsds/ltp/blob/sgx-lkl/testcases/kernel/syscalls/fcntl/fcntl11.c

This is locking and unlocking the regions of the same file. fcntl locks works between processes. So, this test case needs multiple processes to test.
Fork is used to create a child process and a pipe is setup between parent and child. The parent process sets the lock region and does the test by writing to the child pipe and performing a read pipe in child and then validating the result in parent process.
Since fork( ) is not supported, this test can't be performed in SGX-LKL environment.

3) fcntl14 https://github.com/lsds/ltp/blob/sgx-lkl/testcases/kernel/syscalls/fcntl/fcntl14.c

This test executes file locking test cases for fcntl. The test cases are used to lock a file opened
- without mandatory locking,
- with mandatory locking
- mandatory locking with NOBLOCK
The locking is done in parent process and the child process tries to get the status of lock and also does unlcok based on the test case.
Since fork( ) is not supported in SGX-LKL, this test can't be executed.

4) fcntl15 https://github.com/lsds/ltp/blob/sgx-lkl/testcases/kernel/syscalls/fcntl/fcntl15.c

As per the description, fcntl locks(F_SETLK) can only be tested using multiple processes.
The test checks that the file locks are removed when file is closed.
The test needs a parent and two child processes where the parent opens the file and locks and the child closes one file and checks for the lock status of the file.
As fork( ) is not supported in sgx-lkl the test can't be executed.

5) fcntl17 https://github.com/lsds/ltp/blob/sgx-lkl/testcases/kernel/syscalls/fcntl/fcntl17.c

The test checks deadlock detection for file locking. The parent forks off 3 children. The parent controls the children with messages via pipes to create a delayed deadlock between the second and third child and checks for file locking status.
It can't be teted in sgx-lkl due to unavailability of multi process environment.

6) fcntl19 https://github.com/lsds/ltp/blob/sgx-lkl/testcases/kernel/syscalls/fcntl/fcntl19.c

The test verifies checking locking and unlocking of different regions of a file around a write lock.
Fork is used to create a child process and a pipe is setup between parent and child. The parent process sets the lock region and does the test by writing to the child pipe and performing a read pipe in child and then validating the result in parent process.
Since fork( ) is not supported, this test can't be performed in SGX-LKL environment.

7) fcntl20 https://github.com/lsds/ltp/blob/sgx-lkl/testcases/kernel/syscalls/fcntl/fcntl20.c

The test verifies checking locking and unlocking of different regions of a file around a read lock.
Fork is used to create a child process and a pipe is setup between parent and child. The parent process sets the lock region and does the test by writing to the child pipe and performing a read pipe in child and then validating the result in parent process.
Since fork( ) is not supported, this test can't be performed in SGX-LKL environment.

8) fcntl21 https://github.com/lsds/ltp/blob/sgx-lkl/testcases/kernel/syscalls/fcntl/fcntl21.c

The test verifies checking locking of file in parent  and corresponding locking status in child process .
Since fork( ) is not supported, this test can't be performed in SGX-LKL environment.

**Comment by davidchisnall** [comment]
Thanks, that's a great write-up.  I agree on all counts.  We hope to support exec at some point, so please track these with lsds/sgx-lkl#598 is fixed.

**Comment by hukoyu** [comment]
Created issue https://github.com/lsds/ltp/issues/38 to track this. These tests will be categorized unspported and will remain disabled until lsds/sgx-lkl#598 fixed.
